name: db
version: 0.2.4
usage: Recherche une CVE dans la base Trivy
description: Plugin Trivy pour interroger vuln.db avec un CVE-ID
platforms:
  - selector:
    os: darwin
    arch: amd64
    uri: https://github.com/weeros/trivy-plugin-db/releases/download/v0.2.4/trivy_plugin_db_0.2.4_darwin-amd64.tar.gz
    bin: ./db
  - selector:
      os: darwin
      arch: arm64
    uri: https://github.com/weeros/trivy-plugin-db/releases/download/v0.2.4/trivy_plugin_db_0.2.4_darwin-arm64.tar.gz
    bin: ./db
  - selector:
      os: linux
      arch: amd64
    uri: https://github.com/weeros/trivy-plugin-db/releases/download/v0.2.4/trivy_plugin_db_0.2.4_linux-amd64.tar.gz
    bin: ./db
  - selector:
      os: linux
      arch: arm64
    uri: https://github.com/weeros/trivy-plugin-db/releases/download/v0.2.4/trivy_plugin_db_0.2.4_linux-arm64.tar.gz
    bin: ./db